apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert -f docker-compose.yaml -o test
      --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  type: NodePort
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
    nodePort: 30008
  selector:
    io.kompose.service: elasticsearch
status:
  loadBalancer: {}
