apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert -f docker-compose.yaml -o test
      --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: hubapi
  name: hubapi
spec:
  type: NodePort
  ports:
  - name: "9001"
    port: 9001
    targetPort: 9001
    nodePort: 30007
  selector:
    io.kompose.service: hubapi
status:
  loadBalancer: {}
