apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert -f docker-compose.yaml -o test
      --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64.exe convert -f docker-compose.yaml -o test
          --volumes hostPath
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: logstash
    spec:
      containers:
      - image: docker.elastic.co/logstash/logstash:7.8.0
        imagePullPolicy: ""
        name: logstash
        ports:
        - containerPort: 9600
        - containerPort: 7777
        resources: {}
        volumeMounts:
          - mountPath: /usr/share/logstash/pipeline/
            name: config-file
      hostname: logstash
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: config-file
          configMap:
            name: gurukul-logstash-config
            items:
              - key: logstash.conf
                path: logstash.conf
status: {}
