apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: gurukul-mirror-maker2
spec:
    version: 2.8.0
    replicas: 1
    connectCluster: "gurukul-cluster-target"
    clusters:
        - alias: "gurukul-cluster-source"
          bootstrapServers: source-kafka-bootstrap:9092
        - alias: "gurukul-cluster-target"
          bootstrapServers: target-kafka-bootstrap:9092
          config: 
            config.storage.replication.factor: 1
            offset.storage.replication.factor: 1
            status.storage.replication.factor: 1
    mirrors:
        - sourceCluster: "gurukul-cluster-source"
          targetCluster: "gurukul-cluster-target"
          sourceConnector: 
            tasksMax: 1
            config:
                replication.factor: 1 
                offset-syncs.topic.replication.factor: 1
          topicsPattern: "message_topic3"
